from __future__ import annotations

"""Configuration for KG pipeline runtime and LLM calls."""

LLM_API_KEY_ENV = "API_KEY"
LLM_BASE_URL_ENV = "API_BASE_URL"
LLM_MODEL_ENV = "API_MODEL"
LLM_BASE_URL = ""
LLM_MODEL = "qwen3.5-plus"
LLM_REQUIRE_API_KEY = True
LLM_TEMPERATURE = 0.1
LLM_MAX_TOKENS = 4000
LLM_QUALITY_MAX_TOKENS = 500
LLM_QUALITY_SCORE_THRESHOLD = 60
LLM_RETRY_LIMIT = 3
LLM_RETRY_BACKOFF = 2
LLM_MIN_CHUNK_CHARS = 50
LLM_SLEEP_SECONDS = 0.3
LLM_CHECKPOINT_EVERY_CHUNKS = 10
LLM_MOCK_ENV = "KG_PIPELINE_MOCK_LLM"
KG_CHUNK_SIZE = 6000
KG_CHUNK_OVERLAP = 360
KG_MIN_CHUNK_SIZE = 1200
